import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ProviderWrapper } from "./ProviderWrapper";
import Footer from "@/components/front-end/Footer";
import { NavbarCartWrapper } from "@/components/front-end/NavbarCartWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderWrapper>
          <div>
          <NavbarCartWrapper />
          <main>
          {children}

          </main>
        <Footer />
        </div>


        </ProviderWrapper>
        {/* <Footer /> */}
        <Toaster position="bottom-center" reverseOrder={false} />
          </body>
    </html>
  );
}
